#!/usr/bin/env bash
# shellcheck disable=SC2016
# SC2016: the sed scripts here match the literal text `${LIB_DIR}` and
# `${SCRIPT_DIR}` inside the source files. Expanding them would be the bug.
# shellcheck disable=SC2094
# SC2094: $out is written by the redirection on the enclosing block; the
# basename call inside only reads its argument as a string.
# =============================================================================
# build.sh — Flatten the source tree into single self-contained scripts.
#
# The modular layout is right for maintenance and wrong for deployment: getting
# a tool onto a fresh box is usually `scp one-file root@host:` and nothing else.
# This inlines every `source` so the result has no runtime dependency beyond
# bash and shadow-utils.
#
# Usage: ./build.sh [--out dist]
# =============================================================================
set -Eeuo pipefail


SRC_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
OUT_DIR="${SRC_DIR}/dist"

while (( $# > 0 )); do
  case $1 in
    --out) OUT_DIR=${2:?--out requires a path}; shift ;;
    --out=*) OUT_DIR=${1#*=} ;;
    -h|--help) sed -n '2,12p' "${BASH_SOURCE[0]}" | sed 's/^# \?//'; exit 0 ;;
    *) printf 'Unknown option: %s\n' "$1" >&2; exit 64 ;;
  esac
  shift
done

VERSION=$(awk -F'"' '/^USERS_PRO_VERSION=/ {print $2; exit}' "${SRC_DIR}/lib/core.sh")
mkdir -p -- "$OUT_DIR"

# Strip the per-file load guard and shebang from a library before inlining;
# in a single file the guards are noise and the shebangs would be syntax soup.
emit_lib() {
  local path=$1
  printf '\n# ===== inlined: %s =====\n' "${path#"${SRC_DIR}/"}"
  sed -e '1{/^#!/d}' \
      -e '/^\[\[ -n \${_USERS_PRO_[A-Z_]*_LOADED:-} \]\] && return 0$/d' \
      -e '/^_USERS_PRO_[A-Z_]*_LOADED=1$/d' \
      -- "$path"
}

bundle() {
  local entry=$1 out=$2
  shift 2
  local -a libs=("$@")

  {
    printf '#!/usr/bin/env bash\n'
    printf '# =============================================================================\n'
    printf '# %s %s — self-contained build. Generated by build.sh; do not edit.\n' \
           "$(basename -- "$out")" "$VERSION"
    printf '# Source: https://github.com/your-org/users-pro\n'
    printf '# Built:  %s\n' "$(date -u +%FT%TZ)"
    printf '# =============================================================================\n'
    printf '# shellcheck disable=SC2329\n'
    printf '# SC2329: in a flattened bundle ShellCheck cannot see that the entry point\n'
    printf '# dispatches into these library functions. The modular tree lints clean.\n'

    local lib
    for lib in "${libs[@]}"; do
      emit_lib "${SRC_DIR}/lib/${lib}"
    done

    printf '\n# ===== inlined: bin/%s =====\n' "$(basename -- "$entry")"
    # Drop the shebang, the path-resolution preamble and every `source` line:
    # the libraries are already above us.
    sed -e '1{/^#!/d}' \
        -e '/^source "\${LIB_DIR}\//d' \
        -e '/^# shellcheck source=/d' \
        -e '/^_self=/,/^unset _self _target$/d' \
        -- "$entry"
  } >"$out"

  chmod 0755 -- "$out"
  bash -n "$out" || { printf 'Bundle %s failed the syntax check.\n' "$out" >&2; exit 70; }
}

bundle "${SRC_DIR}/bin/users-pro" "${OUT_DIR}/users-pro" \
       core.sh ssh.sh query.sh account.sh

bundle "${SRC_DIR}/bin/users-pro-tui" "${OUT_DIR}/users-pro-tui" \
       core.sh ssh.sh query.sh account.sh tui/term.sh tui/input.sh tui/widgets.sh tui/app.sh

# The CLI shells out to the TUI by path; in a flat bundle they sit side by side.
sed -i 's|local tui="\${SCRIPT_DIR}/users-pro-tui"|local tui="${SCRIPT_DIR:-$(dirname -- "$0")}/users-pro-tui"|' \
  "${OUT_DIR}/users-pro"

printf 'Built %s\n' "$VERSION"
for f in "${OUT_DIR}/users-pro" "${OUT_DIR}/users-pro-tui"; do
  printf '  %-40s %6s lines  %s\n' "$f" "$(wc -l <"$f")" "$(du -h "$f" | cut -f1)"
done
